const symptoms = [
    { name: "감기", main_symptom: ["기침", "콧물"], concordance_rate: 0, url: "https://zrr.kr/x3Te" },
    { name: "외이도염", main_symptom: ["귀 통증", "귀에서 액체", "귀가 잘 안들림", "청력 손실"], url: "https://zrr.kr/B5di" },
    { name: "급성 중이염", main_symptom: ["열", "메스꺼움", "구토", "설사", "귀에서 액체", "두통"], concordance_rate: 0, url: "https://zrr.kr/YpHz" },
    { name: "분비성 중이염", main_symptom: ["먹먹함", "청력 손실", "귀가 잘 안들림", "이명", "귀에서 소리"], concordance_rate: 0, url: "https://zrr.kr/1TlO" },
    { name: "메니에르병", main_symptom: ["어지럼증", "어지러움", "메스꺼움", "구토", "울림", "귀가 잘 안들림", "청력 손실", "멍멍함"], concordance_rate: 0, url: "https://zrr.kr/CEVs" },
    { name: "비염", main_symptom: ["기침", "가려움", "코막힘", "눈 어림", "미열"], concordance_rate: 0, url: "https://zrr.kr/eJAL" },
    { name: "부비동염", main_symptom: ["녹색 콧물", "노란색 콧물", "코막힘", "통증", "열", "오한"], concordance_rate: 0, url: "https://zrr.kr/67tI" },
    { name: "편도염", main_symptom: ["통증", "편도", "부음", "림프절"], concordance_rate: 0, url: "https://zrr.kr/x41A" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
    // { name: "", main_symptom: [], url: "" },
];

module.exports = symptoms;